# BOW

###### https://scikit-learn.org/0.15/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

In [12]:
documents = ["people watch movie and watch movie again", 
             "people watch cricket and watch cricket",
             "people like movie and like movie a lot",
             "people like cricket"]

In [13]:
document=["divesh is a good mentor he teaches us very well he teaches the project"]

AIM: Covert: Data: Number

In [14]:
bow = CountVectorizer()

In [15]:
bow_matrix = bow.fit_transform(documents)

In [16]:
bow_matrix

<4x8 sparse matrix of type '<class 'numpy.int64'>'
	with 17 stored elements in Compressed Sparse Row format>

In [17]:
print("BOW Matrix:\n", bow_matrix.toarray())

BOW Matrix:
 [[1 1 0 0 0 2 1 2]
 [0 1 2 0 0 0 1 2]
 [0 1 0 2 1 2 1 0]
 [0 0 1 1 0 0 1 0]]


In [18]:
bow.get_feature_names_out()

array(['again', 'and', 'cricket', 'like', 'lot', 'movie', 'people',
       'watch'], dtype=object)

In [19]:
print("Vocabulary:", bow.get_feature_names_out())


Vocabulary: ['again' 'and' 'cricket' 'like' 'lot' 'movie' 'people' 'watch']
